Changing default build distances
jaguilar/long-reach pull request #10
Opened 2017-04-26 14:21 UTC by utoxin

You asked for some suggested changes to the default reach distances. Here you go. :)

2017-04-26 18:07 UTC, toric55 commented
seems reasonable enough! i like it.

2017-04-26 18:58 UTC, utoxin commented
Looked through docs on Radar ranges and such, and it looks like 150 (the place range I chose is about the max normal player radar range, while the interact range is a little more than a full on radar.

I /do/ intend to look at creating the config feature you mentioned in the other issue, so for now I think this is a good range.

2017-04-26 20:42 UTC, toric55 commented
according to my testing, 100 is about the reatch of the screen at full zoom out. (can almost reatch the edge to build with data.raw.player.player.build_distance = 100. 
so, maybye build distance at 50, and reatch at 125 or so?

2017-04-26 20:46 UTC, utoxin commented
Yeah, that's probably more what I'll do for my personal play style. But I'm going to be working on another PR tonight to actually add a config interface into the in-game options, so this can be tuned easily by the player. :)

2017-04-26 20:49 UTC, jaguilar commented
The reach and build distances should by default cover the entire zoomed out
ordinary window (equiv behavior to 0.14). Of course, I'm happy if we get
the config API implemented and people can tweak as desired without having
to edit lua files.

On Wed, Apr 26, 2017 at 4:46 PM, Matthew Walker <notifications@github.com>
wrote:

> Yeah, that's probably more what I'll do for my personal play style. But
> I'm going to be working on another PR tonight to actually add a config
> interface into the in-game options, so this can be tuned easily by the
> player. :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jaguilar/long-reach/pull/10#issuecomment-297536199>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAwzTMCILzUfDmnJVz_awZR6E2Dyxzuxks5rz60xgaJpZM4NI7u2>
> .
>

2017-04-26 20:52 UTC, utoxin commented
@jaguilar And with my defaults above they DEFINITELY cover that entire are, plus a bit of extra in the radar view, without allowing interaction with extremely areas. :)

2017-04-26 20:52 UTC, jaguilar commented
OK, sounds good to me. Will review and test when I have my son in bed.
Expect the changes to be merged later tonight.

On Wed, Apr 26, 2017 at 4:52 PM, Matthew Walker <notifications@github.com>
wrote:

> @jaguilar <https://github.com/jaguilar> And with my defaults above they
> DEFINITELY cover that entire are, plus a bit of extra in the radar view,
> without allowing interaction with extremely areas. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jaguilar/long-reach/pull/10#issuecomment-297537525>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAwzTKuVIJGf5Pe2r6YT50-8M-haM0pqks5rz65ygaJpZM4NI7u2>
> .
>

2017-04-26 21:16 UTC, toric55 commented
125 cover the entire view area, and a couple tiles outside.

2017-04-27 00:01 UTC, jaguilar commented on long-reach_0.0.7/data-final-fixes.lua
> +data.raw.player.player.reach_distance = 300
150 units is already a perfectly safe distance for spamming turrets in biter nests. For simplicity, please remove the rationale and set these to the same value. So long as it covers the entire viewport, I don't really care what the amount is.

2017-04-27 00:02 UTC, jaguilar requested changes
Please make this change, then I'll test and we can merge.

2017-04-27 00:02 UTC, utoxin commented on long-reach_0.0.7/data-final-fixes.lua
> +data.raw.player.player.reach_distance = 300
I'm about 90% done writing the version that actually has a settings GUI.

2017-04-27 00:25 UTC, jaguilar commented on long-reach_0.0.7/data-final-fixes.lua
> +data.raw.player.player.reach_distance = 300
OK, sounds good to me. May not review tonight, should do tomorrow. :)

2017-04-27 01:13 UTC, utoxin commented
Made that change for now. The config screen update has hit some snags that I'm researching, so this is the simple solution.

2017-04-27 02:17 UTC, utoxin commented
Made obsolete by #11.

2017-04-27 02:17 UTC, closed without merging